
version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: event-service-db
    restart: always
    environment:
      POSTGRES_DB: event_service
      POSTGRES_USER: event
      POSTGRES_PASSWORD: eventpsw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build: .
    container_name: event-service
    restart: always
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/event_service
      SPRING_DATASOURCE_USERNAME: event
      SPRING_DATASOURCE_PASSWORD: eventpsw
    ports:
      - "8080:8080"

volumes:
  postgres_data:
    driver: local
