
services:
  postgres:
    image: postgres:15
    container_name: event-service-db
    restart: always
    environment:
      POSTGRES_DB: event_service
      POSTGRES_USER: event
      POSTGRES_PASSWORD: eventpsw
    networks:
      - bookfest-event-network
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_event:/var/lib/postgresql/data


volumes:
  postgres_data_event:


networks:
  bookfest-event-network :
    external: true