spring.application.name=user-service

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/user_service
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect





# Configuration du serveur
server.port=8080

# Configuration du logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=INFO

spring.docker.compose.enabled=false

logging.level.org.springframework.security=DEBUG


# Configuration de l'authentification
jwt.secret=ZMHMNOI+DZddoSmF8N8UnKDl/epPlE4/xWns/1YS49o=
jwt.expiration=3600000
jwt.issuer=user-service
